version: '3.9'

services:
  postgres:
    image: postgres:15
    container_name: postgres-nest
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: nestgraphql
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - nest-network

  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin-nest
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "8080:80"
    networks:
      - nest-network

volumes:
  pgdata:

networks:
  nest-network:
    driver: bridge